#Testes para Q-Learning com Numpy

In [ ]:
import numpy as np

In [ ]:
table = np.zeros([5, 4])

In [ ]:
table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
table[0,1] = 5
table[2,2] = 27
table

array([[ 0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0., 27.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [ ]:
table[2, :] #Mostra o conteudo da linha 2

array([ 0.,  0., 27.,  0.])

In [ ]:
np.argmax(table[2, :]) #Obtém o Index da coluna com o maior número

2

In [ ]:
acoes = ["Cima", "Baixo", "Esquerda", "Direita"]

#Ou seja, considerando que o melhor resultado foi o número 27, a resposta desejada é o Índice 2 que representa a ação 2 para o aprendizado por reforço.
#Se as ações fossem [cima, baixo, esquerda, direita], o índice 2 representaria "esquerda" para o agente.

print(f"A melhor ação a partir do estado atual é: {acoes[np.argmax(table[2, :])]}")

A melhor ação a partir do estado atual é: Esquerda


#Exportar e Carregar Numpy Array

In [ ]:
#Digamos que aprendemos a Q-table durante o treinamento e queremos salvar para o teste, podemos usar np.save()
np.save("table_learned.npy", table)

In [ ]:
#Agora que salvamos, podemos carregar com np.load()
table_loaded = np.load("table_learned.npy")
print(table_loaded)

[[ 0.  5.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. 27.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


#Removendo dados Nulos

In [ ]:
#Referência: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html
import pandas as pd
data = [["Sherlon", 28],
        ["Maria", None],
        ["Naldo", 25],
        ["João", None],
        ["Lucas", 0]]
x = pd.DataFrame(data)
x.columns = ["Nome", "Idade"]
x

Nome  Idade
0  Sherlon   28.0
1    Maria    NaN
2    Naldo   25.0
3     João    NaN
4    Lucas    0.0

In [ ]:
#Remove os dados Nulos
x_filtered = x.dropna()

In [ ]:
x_filtered

Nome  Idade
0  Sherlon   28.0
2    Naldo   25.0
4    Lucas    0.0

#Removendo dados inconsistestes (Idade < 18)

In [ ]:
#Apresenta os dados que satisfazem a condição desejada, neste caso Idade >= 18.
x_filtered = x_filtered[x_filtered["Idade"] >= 18]

In [ ]:
x_filtered

Nome  Idade
0  Sherlon   28.0
2    Naldo   25.0

#Exportar e Carregar o DataFrame filtrado

In [ ]:
import pandas as pd
import numpy as np

#Exportar os dados
saida = np.array(x_filtered)
np.save("meus_dados_filtrados.npy", saida)

In [ ]:
#Carregar os dados
entrada = np.load("meus_dados_filtrados.npy", allow_pickle=True)
x_carregado = pd.DataFrame(entrada)
x_carregado

0     1
0  Sherlon  28.0
1    Naldo  25.0